NumPy

In [171]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
# author : Liu Kun
# date   : 2022-12-29 15:00:00

安装NumPy (2选1)
%conda install numpy
%pip install numpy

导入NumPy

In [172]:
import numpy as np

In [173]:
# 使用列表来创建数组
np.array([1, 2, 3])

array([1, 2, 3])

In [174]:
# 全 0 数组
np.zeros(2)

array([0., 0.])

In [175]:
# 全 1 数组
np.ones(2)

array([1., 1.])

In [176]:
# 随机空数组
np.empty(2)

array([1., 1.])

In [177]:
# 指定间隔数组 array + range = arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [178]:
# 指定间隔数组 (均匀间隔)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [179]:
# 指定间隔数组 (间隔内线性排列)
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [180]:
# 指定数据类型
np.ones(3, dtype=np.float64)

array([1., 1., 1.])

In [181]:
# 排序
arr = np.array([5, 2, 4, 3, 1])
np.sort(arr)

array([1, 2, 3, 4, 5])

In [182]:
# 连接
a = np.array([1, 2, 3])
b = np.array([6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 6, 7, 8])

In [183]:
# 也可以这样连接
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [184]:
# 数组的形状和大小
arr = np.array([ [[0, 1, 2, 3],
                  [4, 5, 6, 7]],

                 [[0, 1, 2, 3],
                  [4, 5, 6, 7]],

                 [[0 ,1 ,2, 3],
                  [4, 5, 6, 7]] ])

In [185]:
# 数组维数
arr.ndim

3

In [186]:
# 数组中元素总数
arr.size

24

In [187]:
# 数组形状
arr.shape

(3, 2, 4)

In [188]:
# 重塑数组
arr = np.arange(6)
print('arr: ', arr)
arr.reshape(2, 3)

arr:  [0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

In [189]:
# 添加新轴
arr = np.arange(6)
print('arr.shape: ', arr.shape, arr)
new_arr = arr[np.newaxis, :]
print('new_arr.shape: ', new_arr.shape, new_arr)

arr.shape:  (6,) [0 1 2 3 4 5]
new_arr.shape:  (1, 6) [[0 1 2 3 4 5]]


In [190]:
# 指定位置插入新轴来扩展数组
arr = np.arange(6)
x = np.expand_dims(arr, axis=0)
print(x.shape, x)
y = np.expand_dims(arr, axis=1)
print(y.shape, y)

(1, 6) [[0 1 2 3 4 5]]
(6, 1) [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [191]:
# 索引和切片
arr = np.array([1, 2, 3])
print(arr[1])
print(arr[0:2])
print(arr[1:])
print(arr[-2:])

2
[1 2]
[2 3]
[2 3]


In [192]:
# 还有更骚的操作
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[arr < 7])
print(arr[arr % 2 == 0])
print(arr < 5)

[1 2 3 4 5 6]
[ 2  4  6  8 10 12]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]


In [193]:
# 堆叠
x = np.array([[1, 1],
              [2, 2]])
y = np.array([[3, 3],
              [4, 4]])

In [194]:
# 垂直堆叠
np.vstack((x, y))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [195]:
# 水平堆叠
np.hstack((x, y))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

试一试 vsplit 或 hsplit 吧?

In [196]:
arr_new = np.hstack((x, y))
np.hsplit(arr_new, 2)

[array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]])]

In [197]:
# 浅表副本 or 深层副本
arr = np.arange(6)
bak = arr.copy()
bak[0] = 100
print(arr, bak)

[0 1 2 3 4 5] [100   1   2   3   4   5]


In [198]:
# 加减乘除
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [199]:
data + ones

array([2, 3])

In [200]:
data - ones

array([0, 1])

In [201]:
data * ones

array([1, 2])

In [202]:
data / ones

array([1., 2.])

In [203]:
# 求和
data.sum()

3

In [204]:
# 对轴求和
arr = np.array([[1, 1], [2, 2]])

In [205]:
arr.sum(axis=0)

array([3, 3])

In [206]:
arr.sum(axis=1)

array([2, 4])

In [207]:
# 向量 x 标量
data = np.array([1, 2])
data * 1.6

array([1.6, 3.2])

In [208]:
# 最大/最小值 当然也可以对轴操作
data = np.array([5, 3, 2, 4, 1])

In [209]:
data.min()

1

In [210]:
data.max()

5

In [211]:
# 算术均值
data.mean()

3.0

In [212]:
# 转置
arr = np.arange(6)
x = arr.reshape(2, 3)
print('X', x)
print('X.T', x.T)
print('X.T', x.transpose())

X [[0 1 2]
 [3 4 5]]
X.T [[0 3]
 [1 4]
 [2 5]]
X.T [[0 3]
 [1 4]
 [2 5]]


In [213]:
# 反转数组
arr = np.arange(6)
np.flip(arr)

array([5, 4, 3, 2, 1, 0])

In [214]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [215]:
# 展平
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [216]:
# help ? ??
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [217]:
max?

In [218]:
max??